/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-13-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Player {
    public void playing() {
        string player1Name = 'Hagi';
        string player2Name = 'Alex';
        string player3Name = 'Muslera';
        string player4Name = 'Sergen';
        string player5Name = 'Hami';
        system.debug('Super Lig Player\'s name is ' +player1Name);
        system.debug('Super Lig Player\'s name is ' +player2Name);
        system.debug('Super Lig Player\'s name is ' +player3Name);
        system.debug('Super Lig Player\'s name is ' +player4Name);
        system.debug('Super Lig Player\'s name is ' +player5Name);
    }
}